//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rashad.MOdel
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.Items = new HashSet<Item>();
        }
    
        public string categorie_name { get; set; }
        public int categorie_Id { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
